import Header from '@/components/Header/Header';
import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import '@/app/styles.css';

const figtree = Figtree({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={figtree.className}>
            <body>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
